# Dockerfile para MySQL 8
FROM mysql:8.0

# Definir variáveis de ambiente para inicialização do MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=local_yii2
ENV MYSQL_PASSWORD=root

# Copiar scripts SQL de inicialização, se necessário
# COPY ./docker/db/init.sql /docker-entrypoint-initdb.d/init.sql
